name: jrpn16
version: '2.1.18'
summary: Calculator simulator inspired by the HP-16C Computer Scientist Calculator
description: |
  Calculator simulator inspired by the HP-16C "computer scientist".
  Written in Flutter, so UI scales to any screen size, and the same
  code is used for versions for Android, MacOS and Windows.
  store.

confinement: strict

platforms:
  amd64:
  arm64:

base: core24
grade: stable
license: GPL-3.0+

slots:
    dbus-jrpn16:
        interface: dbus
        bus: session
        name: com.jovial.jrpn

parts:
    jrpn16:
        plugin: flutter
        source: .
        flutter-target: lib/main.dart

apps:
    jrpn16:
        command: jrpn16
        extensions: [gnome]
        plugs:
        - home
        slots:
        - dbus-jrpn16
